language: ruby
rvm:
  - 1.9.3
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake --trace spec
before_script:
  - mysql -e 'create database `nhs-patientlist-test`;'
  - RAILS_ENV=test bundle exec rake --trace db:setup db:test:prepare
