language: ruby
rvm:
  - 1.9.3
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
before_script:
  - mysql -e 'create database `nhs-patientlist-test`;'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
  - rackup  
  - sleep 3 